In [3]:
# 2D array
array_1 = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
print(array_1)
print(array_1[0], ":", array_1[0][0], array_1[0][1], array_1[0][2])
print(type(array_1))


[[1, 2, 3], [4, 5, 6], [7, 8, 9]]
[1, 2, 3] : 1 2 3
<class 'list'>


In [7]:
'''
.shape attribute - returns the dimensions of the array 
in the form of a tuple with the length of the tuple indicating the number of dimensions 
and the elements indicating the size of the array in each dimensionimport numpy as np
'''
import numpy as np

array_2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(array_2, "\n")
print(array_2.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

(3, 3)


In [8]:
'''
.size attribute - returns the total number of elements in the array
'''
print(array_2.size)

9


In [13]:
'''
.ndim attribute - returns the number of dimensions of the array
'''
array_3 = np.array([1, 2, 3])
print(array_3.ndim)

1


In [14]:
'''
.dtype attribute - returns the data type of the elements in the array
'''
print(array_3.dtype)

int64


In [15]:
'''
.reshape method - returns a new array with the specified shape
'''
array_4 = np.array([1, 2, 3, 4, 5, 6])
print(array_4, "\n")
print(array_4.reshape(2, 3))

[1 2 3 4 5 6] 

[[1 2 3]
 [4 5 6]]
