In [5]:
#3D array
array_1 = [[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]

print(array_1)
print(array_1[0], ":", array_1[0][0])
print(array_1[1][0], ":", array_1[1][0][0], array_1[1][0][1], array_1[1][0][2])
print(type(array_1))


[[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]]
[[1, 2, 3], [4, 5, 6]] : [1, 2, 3]
[7, 8, 9] : 7 8 9
<class 'list'>


In [9]:
''' 
.shape attribute - returns the dimensions of the array 
in the form of a tuple with the length of the tuple indicating the number of dimensions 
and the elements indicating the size of the array in each dimension
'''
import numpy as np

array_2 = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(array_2, "\n")
print(array_2.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]] 

(2, 2, 3)


In [10]:
'''
.size attribute - returns the total number of elements in the array
'''
print(array_2.size)

12


In [12]:
'''
.ndim attribute - returns the number of dimensions of the array
'''
print(array_2.ndim)

3


In [13]:
'''
.dtype attribute - returns the data type of the elements in the array
'''
print(array_2.dtype)

int64
