In [7]:
# Initialize 1D array with zeros()
import numpy as np

print(np.zeros(5))

[0. 0. 0. 0. 0.]


In [8]:
# Initialize 2D array with zeros()
print(np.zeros((2, 3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Initialize 3D array with zeros()
print(np.zeros((2, 3, 4)))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


In [10]:
# Initialize 2D array with zeros() and dtype
print(np.zeros((2, 3), dtype=int))

[[0 0 0]
 [0 0 0]]


In [13]:
# Initialize 1D array with full()
print(np.full(5, 3))

# Initialize 2D array with full()
print(np.full((2, 3), 3))

[3 3 3 3 3]
[[3 3 3]
 [3 3 3]]


In [14]:
# 2D array with diemntion 3,4 and value 7
print(np.full((3, 4), 7))

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


In [16]:
# Initialize array with empty()
print(np.empty(5))
print(np.empty((2, 3)))

[1.5e-323 1.5e-323 1.5e-323 1.5e-323 1.5e-323]
[[1.5e-323 1.5e-323 1.5e-323]
 [1.5e-323 1.5e-323 1.5e-323]]
