In [1]:
# Boolean indexing in NumPy
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
condition = arr > 3
print(condition)

[False False False  True  True  True  True  True  True]


In [3]:
# Filtering the array - only the elements that meet the condition
newArr = arr[condition]
print(newArr)

[4 5 6 7 8 9]


In [4]:
# In one line
filtered_arr = arr[arr > 3]
print(filtered_arr)

[4 5 6 7 8 9]


In [5]:
# Filter based on 02 conditions
newArr = arr[(arr > 3) & (arr < 8)]
print(newArr)

[4 5 6 7]
