In [2]:
'''
Create a 2D NumPy array with the shape 4 by 5 conatining the numbers from 1 to 20

1. Perform the following operations on the above matrix:
    - Add 10 to every elemt
    - Multiply every element by 2
    - Calculate the square of each element
'''

import numpy as np

num_array = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10], [11, 12, 13, 14, 15], [16, 17, 18, 19, 20]])
# ----- Or ----- #
num_array = np.array(range(1, 21)).reshape(4, 5)

print("Original Array:")
print(num_array)

print("\nAdding 10 to every element:")
print(num_array + 10)

print("\nMultiplying every element by 2:")
print(num_array * 2)

print("\nCalculating the square of each element:")
print(num_array ** 2)

Original Array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]

Adding 10 to every element:
[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]]

Multiplying every element by 2:
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]]

Calculating the square of each element:
[[  1   4   9  16  25]
 [ 36  49  64  81 100]
 [121 144 169 196 225]
 [256 289 324 361 400]]
