In [3]:
# Creating a numpy array
import numpy as np

array_1 = np.array([6, 10, 11, 1])

print(array_1)
print(type(array_1))

[ 6 10 11  1]
<class 'numpy.ndarray'>


In [2]:
# Adding indexs of 2 arrays using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])
array_2 = np.array([2, 3, 4, 5])

sum_array = array_1 + array_2
print(sum_array)

# ------ Or ------
sum_array = np.add(array_1, array_2)
print(sum_array)

[ 8 13 15  6]
[ 8 13 15  6]


In [1]:
# Subtracting indexs of 2 arrays using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])
array_2 = np.array([2, 3, 4, 5])

sub_array = array_1 - array_2
print(sub_array)

# ------ Or ------
sub_array = np.subtract(array_1, array_2)
print(sub_array)

[ 4  7  7 -4]
[ 4  7  7 -4]


In [3]:
# Multiplying indexs of 2 arrays using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])
array_2 = np.array([2, 3, 4, 5])

mul_array = array_1 * array_2
print(mul_array)

# ------ Or ------
mul_array = np.multiply(array_1, array_2)
print(mul_array)

[12 30 44  5]
[12 30 44  5]


In [4]:
# Dividing indexs of 2 arrays using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])
array_2 = np.array([2, 3, 4, 5])

div_array = array_1 / array_2
print(div_array)

# ------ Or ------
div_array = np.divide(array_1, array_2)
print(div_array)

[3.         3.33333333 2.75       0.2       ]
[3.         3.33333333 2.75       0.2       ]


In [12]:
# Getting the root of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

root_array = np.power(array_1, 2)
print(root_array)

# ------ Or ------
root_array = array_1 ** 2
print(root_array)

[ 36 100 121   1]
[ 36 100 121   1]


In [10]:
# Getting square root of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

sqrt_array = np.sqrt(array_1)
print(sqrt_array)

# ------ Or ------
sqrt_array = array_1 ** 0.5
print(sqrt_array)

[2.44948974 3.16227766 3.31662479 1.        ]
[2.44948974 3.16227766 3.31662479 1.        ]


In [13]:
# Getting the sum of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

sum_array = np.sum(array_1)
print(sum_array)

28


In [3]:
# Getting the mean of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

mean_array = np.mean(array_1)
print(mean_array)

7.0


In [16]:
# Getting the median of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

median_array = np.median(array_1)
print(median_array)

8.0


In [5]:
# Getting maximum value of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

max_array = np.max(array_1)
print(max_array)

11


In [17]:
# Getting minimum value of an array using numpy
import numpy as np

array_1 = np.array([6, 10, 11, 1])

min_array = np.min(array_1)
print(min_array)

1
